class Assignment {
  final String id;           // UUID from Supabase
  final String classCode;
  final String teacherId;
  final String bookId;
  final String bookTitle;
  final String unitId;
  final String unitTitle;
  final String? dueDate;     // 'YYYY-MM-DD' or null
  final int wordCount;
  final DateTime createdAt;
  final bool isActive;

  const Assignment({
    required this.id,
    required this.classCode,
    required this.teacherId,
    required this.bookId,
    required this.bookTitle,
    required this.unitId,
    required this.unitTitle,
    this.dueDate,
    required this.wordCount,
    required this.createdAt,
    required this.isActive,
  });

  factory Assignment.fromMap(Map<String, dynamic> map) {
    return Assignment(
      id: map['id'] as String,
      classCode: map['class_code'] as String,
      teacherId: map['teacher_id'] as String,
      bookId: map['book_id'] as String,
      bookTitle: map['book_title'] as String,
      unitId: map['unit_id'] as String,
      unitTitle: map['unit_title'] as String,
      dueDate: map['due_date'] as String?,
      wordCount: map['word_count'] as int,
      createdAt: DateTime.parse(map['created_at'] as String),
      isActive: map['is_active'] as bool,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'class_code': classCode,
      'teacher_id': teacherId,
      'book_id': bookId,
      'book_title': bookTitle,
      'unit_id': unitId,
      'unit_title': unitTitle,
      'due_date': dueDate,
      'word_count': wordCount,
      'is_active': isActive,
      // id and created_at are generated by Supabase — do NOT include on insert
    };
  }

  // Returns true if the due date is today or in the past
  bool get isOverdue {
    if (dueDate == null) return false;
    final due = DateTime.parse(dueDate!);
    final today = DateTime.now();
    return DateTime(today.year, today.month, today.day)
        .isAfter(DateTime(due.year, due.month, due.day));
  }

  // Days remaining until due date. Returns null if no due date.
  int? get daysRemaining {
    if (dueDate == null) return null;
    final due = DateTime.parse(dueDate!);
    final today = DateTime.now();
    return due.difference(DateTime(today.year, today.month, today.day)).inDays;
  }
}
