name: Build Flutter App

on:
  push:
    branches:
      - main

env:
  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
  CHAT_ID: ${{ secrets.CHAT_ID }}

jobs:
  build_android:
    name: Build Android App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          cache: true

      - name: Cache pub dependencies
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Install dependencies
        run: flutter pub get

      - name: Create key.properties
        run: |
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> android/key.properties
          echo "storeFile=keystore.jks" >> android/key.properties

      - name: Decode keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/keystore.jks

      - name: Build Android APK
        run: |
          flutter build apk --release --split-per-abi \
            --dart-define=SUPABASE_URL=${{ secrets.SUPABASE_URL }} \
            --dart-define=SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}

      - name: Upload APK to Telegram
        run: |
          VERSION="v1.0.${{ github.run_number }}"
          COMMENT=$(git log -1 --pretty=%B)
          APK_SRC="build/app/outputs/flutter-apk/app-arm64-v8a-release.apk"
          APK_DST="build/app/outputs/flutter-apk/vocab_game-${VERSION}.apk"

          mv "$APK_SRC" "$APK_DST"

          curl -F "document=@${APK_DST}" \
               -F "chat_id=${CHAT_ID}" \
               -F "caption=Android APK ${VERSION}
          ${COMMENT}" \
               "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendDocument"